# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Back_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(default='bookname', max_length=32)),
                ('bookauthor', models.TextField(null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('stata', models.IntegerField(null=True)),
                ('bookuser', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Book_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(default='bookname', max_length=32)),
                ('bookauthor', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Borrow_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(default='bookname', max_length=32)),
                ('bookauthor', models.TextField(null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('stata', models.IntegerField(null=True)),
                ('bookuser', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='user', max_length=20)),
                ('password', models.TextField(max_length=20)),
            ],
        ),
    ]
